import { test, expect } from '@playwright/test';
import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
let bundle:string,css:string;
const root=process.cwd();
test.beforeAll(async()=>{
 const mocks:Record<string,string>={
 'hooks/useAuth':`export function useAuth(){return {user:null,isAuthenticated:false,signInWithEmail:async()=>{window.authCalls=(window.authCalls||0)+1},createAccountWithEmail:async()=>{},signInWithProvider:async()=>{}}}`,
 'lib/authLogin':`export async function googleLogin(){}`,
 'hooks/usePreferredName':`export function usePreferredName(){return {uid:'owner',preferredName:'',loading:false,error:null,updatePreferredName:async value=>{window.savedName=value},retry:()=>{}}}`,
 'hooks/useEntitlements':`export function useEntitlements(){return {phase:'expiredReadOnly',paidPro:false,isReadOnlyMode:true,hasFullAccess:false}}`,
 'hooks/useFullAccessProduct':`export function useFullAccessProduct(){return {status:'available',product:{price:'12,99 €',productId:'flicklet_full_access'}}}`,
 'lib/backupPersistence':`export async function createBackup(){return {createdAt:'2026-10-01'}} export async function restoreBackup(){}`,
 'lib/startOver':`export async function startOver(){window.resetCalls=(window.resetCalls||0)+1;throw Error('SECRET')}`,
 'lib/proUpgrade':`export function startProUpgrade(){} export function restoreFullAccess(){} export function isAndroidBillingAvailable(){return false}`,
 'lib/settings':`export function useSettings(){return {layout:{},notifications:{},personality:'Zen'}} export const settingsManager={};export function resolveFlickletLine(){return ''}`,
 'lib/customLists':`export function useCustomLists(){return {customLists:[],maxLists:3}}export const customListManager={}`,
 'lib/storage':`export function useLibrary(){return []} export const Library={getAll:()=>[]}`,
 'hooks/useAdminRole':`export function useAdminRole(){return {isAdmin:false}}`,
 'components/modals/SharingModal':`export default function Sharing(){return null}`,
 'components/ResetSettingsButton':`export default function Reset(){return null}`,
 'components/ForYouGenreConfig':`export default function Genres(){return null}`,
 'components/modals/NotificationCenter':`export function NotificationCenter(){return null}`,
 'pages/AdminExtrasPage':`export default function Admin(){return null}`,
 };
 const result=await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import AuthModal from './src/components/AuthModal';import PreferredNamePromptModal from './src/components/PreferredNamePromptModal';import StartOverControl from './src/components/StartOverControl';import {renderSettingsSection} from './src/components/settingsSections';import {changeLanguage} from './src/lib/language';const surface=new URLSearchParams(location.search).get('surface');window.localize=changeLanguage;changeLanguage('es');createRoot(document.getElementById('root')).render(surface==='auth'||surface==='blocked'?<AuthModal isOpen onClose={()=>{window.closed=true}}/>:surface==='preferred'?<PreferredNamePromptModal isOpen onClose={()=>{window.closed=true}}/>:surface==='access'?renderSettingsSection('pro',{}):surface==='data'?renderSettingsSection('data',{}):<StartOverControl/>);`,resolveDir:root,loader:'tsx'},bundle:true,write:false,format:'iife',jsx:'automatic',define:{'import.meta.env':'{}'},plugins:[{name:'boundaries',setup(builder){builder.onResolve({filter:/^(\.\.?\/|@\/)/},args=>{const absolute=path.resolve(args.path.startsWith('@/')?path.join(root,'src'):args.resolveDir,args.path.replace(/^@\//,'')).replace(/\.(tsx?|jsx?)$/,'');for(const key of Object.keys(mocks))if(absolute===path.join(root,'src',key))return{path:key,namespace:'mock'};return undefined;});builder.onLoad({filter:/.*/,namespace:'mock'},args=>({contents:mocks[args.path],resolveDir:root,loader:'tsx'}));}}]});
 bundle=result.outputFiles[0].text;const dir=path.join(root,'dist/assets');const name=fs.readdirSync(dir).find(n=>n.startsWith('appBootstrap-')&&n.endsWith('.css'));if(!name)throw Error('Build first');css=fs.readFileSync(path.join(dir,name),'utf8');
});
async function open(page:any,surface:string,width:number,height=667){await page.setViewportSize({width,height});if(surface==='blocked')await page.addInitScript(()=>{Object.defineProperty(navigator,'userAgent',{value:'Instagram'});});await page.route('http://account.test/**',(route:any)=>route.fulfill({contentType:'text/html',body:`<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><main id="root" style="padding:8px"></main><script>${bundle}</script></body></html>`}));await page.goto('http://account.test/?surface='+surface);}
async function contained(page:any){expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize().width);for(const dialog of await page.getByRole('dialog').all()){expect(await dialog.evaluate((el:any)=>el.scrollWidth<=el.clientWidth)).toBe(true);const box=await dialog.boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(page.viewportSize().width);}}
for(const width of [320,360,390,768,1023,1024,1280]){
 test(`Auth and live drafts at ${width}`,async({page})=>{await open(page,'auth',width);await page.getByRole('button',{name:'Iniciar sesión con Email',exact:true}).click();const email=page.getByLabel('Correo electrónico'),password=page.getByLabel('Contraseña');await email.fill('my@example.com');await password.fill('123456');await contained(page);await page.evaluate(()=> (window as any).localize('en'));await expect(page.getByLabel('Email')).toHaveValue('my@example.com');await page.evaluate(()=> (window as any).localize('es'));await expect(page.getByLabel('Contraseña')).toHaveValue('123456');await page.getByRole('button',{name:/^Iniciar sesión$/i}).scrollIntoViewIfNeeded();await page.getByRole('button',{name:/^Iniciar sesión$/i}).click();expect(await page.evaluate(()=> (window as any).authCalls)).toBe(1);});
 test(`Blocked recovery at ${width}`,async({page})=>{await open(page,'blocked',width);await expect(page.getByRole('link',{name:'Abrir en el navegador'})).toBeVisible();await contained(page);await expect(page.getByRole('button',{name:/Google/})).toBeDisabled();});
 test(`Preferred name at ${width}`,async({page})=>{await open(page,'preferred',width);await page.getByLabel('Nombre preferido en Flicklet').fill('Mi Nombre');await contained(page);await page.evaluate(()=> (window as any).localize('en'));await expect(page.getByLabel('Flicklet preferred name')).toHaveValue('Mi Nombre');await page.evaluate(()=> (window as any).localize('es'));await page.getByRole('button',{name:'Ahora no',exact:true}).click();expect(await page.evaluate(()=> (window as any).savedName)).toBeUndefined();});
 test(`Access and Data controls at ${width}`,async({page})=>{await open(page,'access',width);await expect(page.getByRole('heading',{name:'Acceso completo',exact:true})).toBeVisible();await expect(page.getByText(/La compra y la restauración de compras están disponibles/)).toBeVisible();await contained(page);await page.evaluate(()=> (window as any).localize('en'));await expect(page.getByRole('heading',{name:'Full Access',exact:true})).toBeVisible();await open(page,'data',width);await expect(page.getByRole('button',{name:/Descargar copia de seguridad/})).toBeVisible();await page.getByRole('button',{name:/Restaurar desde una copia de seguridad/}).scrollIntoViewIfNeeded();await contained(page);});
 test(`Start Over long warning at ${width}`,async({page})=>{await open(page,'reset',width);await page.getByRole('button',{name:'Empezar de nuevo',exact:true}).click();const dialog=page.getByRole('dialog');await contained(page);await dialog.getByRole('button',{name:'Continuar sin copia de seguridad'}).click();await page.getByLabel('Escribe DELETE para confirmar').fill('DELETE');await page.evaluate(()=> (window as any).localize('en'));await expect(page.getByLabel('Type DELETE to confirm')).toHaveValue('DELETE');await page.evaluate(()=> (window as any).localize('es'));await contained(page);await dialog.getByRole('button',{name:'Empezar de nuevo',exact:true}).scrollIntoViewIfNeeded();await dialog.getByRole('button',{name:'Empezar de nuevo',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('No se pudo empezar de nuevo.');expect(await page.evaluate(()=> (window as any).resetCalls)).toBe(1);await dialog.getByRole('button',{name:'Cancelar'}).click();await expect(dialog).toHaveCount(0);});
}
for(const surface of ['auth','preferred','reset'])test(`${surface} actions remain reachable at keyboard-like reduced height`,async({page})=>{await open(page,surface,320,340);if(surface==='auth'){await page.getByRole('button',{name:/Email/}).click();await page.getByLabel('Correo electrónico').fill('test@example.com');await page.getByLabel('Contraseña').fill('123456');await page.getByRole('button',{name:/^Iniciar sesión$/i}).scrollIntoViewIfNeeded();await expect(page.getByRole('button',{name:/^Iniciar sesión$/i})).toBeInViewport();}else if(surface==='preferred'){await page.getByLabel('Nombre preferido en Flicklet').fill('Name');await page.getByRole('button',{name:'Guardar'}).scrollIntoViewIfNeeded();await expect(page.getByRole('button',{name:'Guardar'})).toBeInViewport();}else{await page.getByRole('button',{name:'Empezar de nuevo',exact:true}).click();await page.getByRole('button',{name:'Continuar sin copia de seguridad'}).click();await page.getByLabel('Escribe DELETE para confirmar').fill('DELETE');await page.getByRole('dialog').getByRole('button',{name:'Empezar de nuevo',exact:true}).scrollIntoViewIfNeeded();await expect(page.getByRole('dialog').getByRole('button',{name:'Empezar de nuevo',exact:true})).toBeInViewport();}await contained(page);});
