import {test,expect} from '@playwright/test';
import {build} from 'esbuild';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');let bundle:string,css:string;
test.beforeAll(async()=>{
 const mocks:Record<string,string>={
 'lib/proUpgrade':`export function startProUpgrade(){}`,
 'hooks/useEntitlements':`export function useEntitlements(){return {hasFullAccess:true}}`,
 'hooks/usePreferredName':`export function usePreferredName(){return {preferredName:'User Name'}}`,
 'lib/storage':`export const Library={getAll:()=>[],getByList:()=>[],subscribe:()=>()=>{}}`,
 'lib/settings':`export function useSettings(){return {personalityLevel:2}}export {resolveFlickletLine} from './flickletPersonality';`,
 'lib/extras/extrasProvider':`export const extrasProvider={fetchExtras:async()=>({kind:'success',videos:Array.from({length:9},(_,i)=>({id:String(i),title:'Provider video title remains unchanged '+i,channelName:'Netflix',thumbnail:'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg"/>',publishedAt:'2020-01-01',provider:'youtube',canEmbed:true,embedUrl:'about:blank'}))}),fetchBloopers:async()=>({kind:'no-content',videos:[]})}`
 };
 const result=await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import {ExtrasModal} from './src/components/extras/ExtrasModal';import {BloopersModal} from './src/components/extras/BloopersModal';import {GoofsModal} from './src/components/extras/GoofsModal';import HomeMarquee from './src/components/HomeMarquee';import {PersonalityBanner} from './src/components/PersonalityBanner';import VoiceSearch from './src/components/VoiceSearch';import {getFlickletMarqueeMessages} from './src/lib/flickletPersonality';import {languageManager,useLanguage} from './src/lib/language';window.contentLocale=l=>languageManager.setLanguage(l);localStorage.setItem('flag:voice_search_enabled','true');window.SpeechRecognition=class {start(){}stop(){}};function App(){useLanguage();const [view,setView]=React.useState('home');window.contentView=setView;return <>{view==='home'&&<><HomeMarquee messages={getFlickletMarqueeMessages(3)}/><PersonalityBanner/><div style={{padding:16}}><VoiceSearch onVoiceResult={()=>{}}/></div></>}{view==='insights'&&<GoofsModal isOpen onClose={()=>setView('home')} tmdbId={2316} title="A long user title whose identity must remain unchanged"/>}{view==='extras'&&<ExtrasModal isOpen onClose={()=>setView('home')} showId={8} showTitle="A long user title whose identity must remain unchanged"/>}{view==='bloopers'&&<BloopersModal isOpen onClose={()=>setView('home')} showId={8} showTitle="A long user title whose identity must remain unchanged"/>}</>}createRoot(document.getElementById('root')).render(<App/>);`,resolveDir:root,loader:'tsx'},bundle:true,write:false,format:'iife',define:{'import.meta.env':'{}','process.env.NODE_ENV':'"production"'},plugins:[{name:'boundaries',setup(b){b.onLoad({filter:/\.[tj]sx?$/},args=>{const name=path.relative(path.join(root,'src'),args.path).replaceAll('\\','/').replace(/\.[tj]sx?$/,'');return mocks[name]?{contents:mocks[name],loader:'tsx',resolveDir:path.dirname(args.path)}:undefined})}}]});bundle=result.outputFiles[0].text;const assets=path.join(root,'dist/assets');css=fs.readFileSync(path.join(assets,fs.readdirSync(assets).find(f=>f.startsWith('appBootstrap-')&&f.endsWith('.css'))!),'utf8');
});
for(const width of [320,360,390,768,1023,1024,1280])test(`personality insights extras voice EN ES EN at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:800});await page.route('https://content.test/**',r=>r.fulfill({contentType:'text/html',body:'<html><body><div id="root"></div></body></html>'}));await page.goto('https://content.test');await page.addStyleTag({content:css});await page.addScriptTag({content:bundle});
 for(const view of ['home','insights','extras','bloopers']){await page.evaluate(v=>(window as any).contentView(v),view);for(const lang of ['en','es','en']){await page.evaluate(l=>(window as any).contentLocale(l),lang);
 if(view==='home'){await expect(page.getByRole('button',{name:lang==='es'?'Iniciar búsqueda por voz':'Start voice search'})).toBeVisible();const track=page.locator('.flicklet-marquee-track').first();const x=await track.evaluate(el=>el.getBoundingClientRect().x);await page.waitForTimeout(250);expect(await track.evaluate(el=>el.getBoundingClientRect().x)).toBeLessThan(x);await page.emulateMedia({reducedMotion:'reduce'});await expect(track).toHaveCSS('animation-name','none');await page.emulateMedia({reducedMotion:'no-preference'});
 }else{const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();const close=dialog.getByRole('button',{name:lang==='es'?'Cerrar ventana':'Close modal',exact:true});await expect(close).toBeVisible();const box=await close.boundingBox();expect(box!.width).toBeGreaterThanOrEqual(44);expect(box!.height).toBeGreaterThanOrEqual(44);expect(box!.x+box!.width).toBeLessThanOrEqual(width);expect(box!.y+box!.height).toBeLessThanOrEqual(800);if(view==='extras'){await expect(page.getByText('Provider video title remains unchanged 0')).toBeVisible();await dialog.getByRole('button',{name:/Provider video title remains unchanged 0/}).click();const playerClose=page.getByRole('button',{name:lang==='es'?'Cerrar reproductor de vídeo':'Close video player'});await expect(playerClose).toBeVisible();const playerBox=await playerClose.boundingBox();expect(playerBox!.height).toBeGreaterThanOrEqual(44);expect(playerBox!.y+playerBox!.height).toBeLessThanOrEqual(800);await expect(page.locator('iframe')).toHaveAttribute('title','Provider video title remains unchanged 0');await playerClose.click();}if(view==='insights')await expect(page.getByText(lang==='es'?/parrilla George Foreman/:/grill injury/)).toBeVisible();}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }}
});
