import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { Library, flushPendingSaves, addToListWithConfirmation } from '../storage';
import { setNotInterested, setPrimaryStatus } from '../statusTransitions';
import { reconcileSeriesReminders, enableSeriesReminder, isSeriesReminderEnabled } from '../seriesReminders';
import { setGlobalToastCallback } from '../toastBridge';
const m = vi.hoisted(() => ({ uid: null as string | null, canWrite: true, native: true, cancel: vi.fn(), schedule: vi.fn(), pending: vi.fn(), episodes: vi.fn(), toast: vi.fn() }));
vi.mock('../auth', () => ({ authManager: { getCurrentUser: () => m.uid ? { uid: m.uid } : null } }));
vi.mock('../customLists', () => ({ customListManager: { updateItemCount: vi.fn() } }));
vi.mock('../readOnlyGuard', () => ({ guardMutation: () => m.canWrite }));
vi.mock('../tmdb', () => ({ getTVShowDetails: vi.fn().mockRejectedValue(Error('offline')) }));
vi.mock('@/tmdb/tv', () => ({ fetchRelevantSeasonEpisodes: m.episodes }));
vi.mock('@capacitor/core', () => ({ Capacitor: { isNativePlatform: () => m.native, getPlatform: () => 'android' } }));
vi.mock('@capacitor/local-notifications', () => ({ LocalNotifications: { getPending: m.pending, cancel: m.cancel, schedule: m.schedule, checkPermissions: async () => ({ display: 'granted' }), createChannel: async () => undefined } }));
const tv = { id: '8', mediaType: 'tv' as const, title: 'Series', userRating: 4, userNotes: 'Notes', tags: ['tag'], isFavorite: true };
function seed() { Library.upsert(tv, 'watching'); Library.addToCustomList(tv, 'a'); Library.addToCustomList(tv, 'b'); localStorage.setItem('episode-progress-8', '{"episodes":{"S1E1":true}}'); localStorage.setItem('flicklet.series-reminders.v1', JSON.stringify({8:{showId:8,title:'Series',enabled:true,updatedAt:1}})); }
beforeEach(() => { localStorage.clear(); window.dispatchEvent(new Event('library:cleared')); m.uid=null; m.canWrite=true; m.native=true; m.cancel.mockReset().mockResolvedValue(undefined); m.schedule.mockReset().mockResolvedValue(undefined); m.pending.mockReset().mockResolvedValue({notifications:[{id:81,extra:{flickletSeriesReminder:true,showId:8}},{id:91,extra:{flickletSeriesReminder:true,showId:9}}]}); m.episodes.mockReset().mockResolvedValue([]); m.toast.mockClear(); setGlobalToastCallback(m.toast); });
afterEach(() => { flushPendingSaves(); vi.restoreAllMocks(); });
it.each([null,'owner'])('preserves content/progress and uses normal persistence for account %s', async uid => { m.uid=uid; seed(); const addedAt=Library.getEntry('8','tv')!.addedAt; const sync=vi.fn(); window.addEventListener('library:changed',sync); expect(await setNotInterested(tv)).toBe(true); flushPendingSaves(); expect(Library.getEntry('8','tv')).toMatchObject({...tv,list:'not',customListIds:['a','b'],addedAt}); expect(Library.getByList('watching')).toHaveLength(0); expect(Library.getByList('not')).toHaveLength(1); expect(Library.getByList('custom:a')).toHaveLength(1); expect(isSeriesReminderEnabled(8)).toBe(false); expect(m.cancel).toHaveBeenCalledWith({notifications:[{id:81}]}); expect(localStorage.getItem('episode-progress-8')).toBe('{"episodes":{"S1E1":true}}'); expect(JSON.parse(localStorage.getItem('flicklet.library.v2')!)['tv:8'].list).toBe('not'); if(uid) expect(sync).toHaveBeenCalled(); window.removeEventListener('library:changed',sync); await reconcileSeriesReminders({force:true}); expect(m.episodes).not.toHaveBeenCalled(); });
it('native cancellation failure preserves prior Library status and preference, reports failure',async()=>{seed();m.cancel.mockRejectedValueOnce(Error('native failure'));expect(await setNotInterested(tv)).toBe(false);expect(Library.getCurrentList('8','tv')).toBe('watching');expect(isSeriesReminderEnabled(8)).toBe(true);expect(m.schedule).toHaveBeenCalled();expect(m.toast).toHaveBeenCalledWith(expect.stringContaining('native failure'),'error');});
it('does not change status until native cancellation completes',async()=>{seed();let done!:()=>void;m.cancel.mockImplementationOnce(()=>new Promise<void>(resolve=>done=resolve));const action=setNotInterested(tv);await vi.waitFor(()=>expect(done).toBeDefined());expect(Library.getCurrentList('8','tv')).toBe('watching');done();await action;expect(Library.getCurrentList('8','tv')).toBe('not');});
it('Search confirmation helper uses canonical cancellation before its completion callback',async()=>{seed();vi.spyOn(window,'confirm').mockReturnValue(true);const complete=vi.fn();addToListWithConfirmation(tv,'not',complete);await vi.waitFor(()=>expect(complete).toHaveBeenCalledOnce());expect(m.cancel).toHaveBeenCalled();expect(isSeriesReminderEnabled(8)).toBe(false);});
it('restoration retains data and does not re-enable reminders',async()=>{seed();await setNotInterested(tv);setPrimaryStatus(tv,'wishlist');expect(Library.getEntry('8','tv')).toMatchObject({...tv,list:'wishlist',customListIds:['a','b']});expect(isSeriesReminderEnabled(8)).toBe(false);expect(localStorage.getItem('episode-progress-8')).not.toBeNull();});
it('reconciliation and enabling cannot schedule a loaded Not Interested title',async()=>{seed();Library.move('8','tv','not');await reconcileSeriesReminders({force:true});expect(m.episodes).not.toHaveBeenCalled();expect(m.cancel).not.toHaveBeenCalled();expect(await enableSeriesReminder(8,'Series')).toMatchObject({enabled:false});expect(m.schedule).not.toHaveBeenCalled();});
it('blocked access does not cancel or mutate',async()=>{seed();m.canWrite=false;expect(await setNotInterested(tv)).toBe(false);expect(m.cancel).not.toHaveBeenCalled();expect(Library.getCurrentList('8','tv')).toBe('watching');});
it('movie with identical ID never cancels TV reminders',async()=>{seed();const movie={...tv,mediaType:'movie' as const};await setNotInterested(movie);expect(Library.getCurrentList('8','tv')).toBe('watching');expect(Library.getCurrentList('8','movie')).toBe('not');expect(m.cancel).not.toHaveBeenCalled();});

it('legacy custom-primary membership survives canonical Not Interested',async()=>{Library.upsert(tv,'custom:a');await setNotInterested(tv);expect(Library.getEntry('8','tv')).toMatchObject({list:'not',customListIds:['a']});expect(Library.getByList('custom:a')).toHaveLength(1);});
it('Search cancellation failure does not remove its result or call completion',async()=>{seed();vi.spyOn(window,'confirm').mockReturnValue(true);m.cancel.mockRejectedValueOnce(Error('native failure'));const complete=vi.fn();addToListWithConfirmation(tv,'not',complete);await vi.waitFor(()=>expect(m.toast).toHaveBeenCalled());expect(complete).not.toHaveBeenCalled();expect(Library.getCurrentList('8','tv')).toBe('watching');});

it('reminder preference write failure recovers schedules and retains status',async()=>{seed();const original=Storage.prototype.setItem;vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,key,value){if(key==='flicklet.series-reminders.v1')throw Error('preference failure');return original.call(this,key,value)});expect(await setNotInterested(tv)).toBe(false);expect(Library.getCurrentList('8','tv')).toBe('watching');expect(isSeriesReminderEnabled(8)).toBe(true);expect(m.schedule).toHaveBeenCalled();expect(m.toast).toHaveBeenCalledWith(expect.stringContaining('preference failure'),'error');});
it('native recovery failure is reported without changing status or preference',async()=>{seed();m.cancel.mockRejectedValueOnce(Error('cancel failure'));m.schedule.mockRejectedValueOnce(Error('recovery failure'));expect(await setNotInterested(tv)).toBe(false);expect(Library.getCurrentList('8','tv')).toBe('watching');expect(isSeriesReminderEnabled(8)).toBe(true);expect(m.toast).toHaveBeenCalledWith(expect.stringContaining('could not be recovered'),'error');});

it('backup round trip retains Not Interested content and permits normal restoration',async()=>{seed();await setNotInterested(tv);flushPendingSaves();const {parseBackup,restoreWrites,applyRestore,portableSettings}=await import('../backup');const {DEFAULT_SETTINGS}=await import('../settings');const backup=parseBackup(JSON.stringify({type:'flicklet-backup',schemaVersion:1,appVersion:'2.0.22',createdAt:new Date().toISOString(),library:Library.getAll(),customLists:[{id:'a',name:'A',createdAt:1},{id:'b',name:'B',createdAt:1}],settings:portableSettings(DEFAULT_SETTINGS),preferredName:'TJ',local:{'episode-progress-8':JSON.parse(localStorage.getItem('episode-progress-8')!)}}));window.dispatchEvent(new Event('library:cleared'));await applyRestore(restoreWrites(backup,localStorage,null),localStorage,async()=>undefined,()=>true);Library.reloadFromStorage(true);expect(Library.getEntry('8','tv')).toMatchObject({...tv,list:'not',customListIds:['a','b']});setPrimaryStatus(tv,'watching');expect(Library.getEntry('8','tv')).toMatchObject({...tv,list:'watching',customListIds:['a','b']});expect(localStorage.getItem('episode-progress-8')).toContain('S1E1');});

it('a newer status choice during cancellation is not overwritten by the pending action',async()=>{seed();let done!:()=>void;m.cancel.mockImplementationOnce(()=>new Promise<void>(r=>done=r));const pending=setNotInterested(tv);await vi.waitFor(()=>expect(done).toBeDefined());setPrimaryStatus(tv,'wishlist');done();expect(await pending).toBe(false);expect(Library.getCurrentList('8','tv')).toBe('wishlist');expect(isSeriesReminderEnabled(8)).toBe(false);});
