import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { buildShowShareUrl, formatListShareText, formatShareSections, getAppOrigin, shareListWithFallback, shareShowWithFallback, shareTextWithFallback } from '../shareLinks';
const write = vi.fn(); const native = vi.fn(); const success = vi.fn(); const error = vi.fn();
beforeEach(() => { vi.clearAllMocks(); vi.stubEnv('VITE_PUBLIC_BASE_URL', 'https://flicklet.netlify.app'); Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:write}}); Object.defineProperty(navigator,'share',{configurable:true,value:native}); Object.defineProperty(navigator,'userAgentData',{configurable:true,value:{mobile:false}}); write.mockResolvedValue(undefined); native.mockResolvedValue(undefined); });
afterEach(() => vi.unstubAllEnvs());
const callbacks = { onSuccess: success, onError: error };
const share = () => shareTextWithFallback({ title: 'List', text: 'Snapshot', ...callbacks });
const mobile = () => Object.defineProperty(navigator,'userAgentData',{configurable:true,value:{mobile:true}});
it('desktop copies text once',async()=>{expect(await share()).toBe('copied');expect(write).toHaveBeenCalledWith('Snapshot');expect(native).not.toHaveBeenCalled();expect(success).toHaveBeenCalledOnce();expect(success).toHaveBeenCalledWith('copied');expect(error).not.toHaveBeenCalled();});
it('native success reports shared, not copied',async()=>{mobile();expect(await share()).toBe('shared');expect(success).toHaveBeenCalledOnce();expect(success).toHaveBeenCalledWith('shared');expect(write).not.toHaveBeenCalled();});
it('cancellation is silent',async()=>{mobile();native.mockRejectedValue(new DOMException('Cancel','AbortError'));expect(await share()).toBe('cancelled');expect(success).not.toHaveBeenCalled();expect(error).not.toHaveBeenCalled();expect(write).not.toHaveBeenCalled();});
it('native failure then copy succeeds without premature error',async()=>{mobile();native.mockRejectedValue(new Error('Native'));expect(await share()).toBe('copied');expect(error).not.toHaveBeenCalled();expect(success).toHaveBeenCalledOnce();});
it.each([true,false])('final failure is reported exactly once (mobile=%s)',async(isMobile)=>{if(isMobile)mobile();native.mockRejectedValue(new Error('Native'));write.mockRejectedValue(new Error('Clipboard'));expect(await share()).toBe('failed');expect(error).toHaveBeenCalledOnce();expect(success).not.toHaveBeenCalled();});
it('unavailable clipboard reports failure',async()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:undefined});expect(await share()).toBe('failed');expect(error).toHaveBeenCalledOnce();});
it('configured origin and mobile production fallback are canonical',()=>{expect(getAppOrigin()).toBe('https://flicklet.netlify.app');vi.stubEnv('VITE_PUBLIC_BASE_URL','');vi.stubEnv('MODE','mobile');vi.stubEnv('DEV',false);expect(getAppOrigin()).toBe('https://flicklet.netlify.app');});
it('development uses local origin without an explicit public base',()=>{vi.stubEnv('VITE_PUBLIC_BASE_URL','');vi.stubEnv('MODE','development');vi.stubEnv('DEV',true);expect(getAppOrigin()).toBe(window.location.origin);});
it.each(['tv','movie'])('link carries exact %s identity',async(mediaType)=>{const url=new URL(buildShowShareUrl({tmdbId:123,mediaType}));expect(url.searchParams.get('mediaType')).toBe(mediaType);expect(url.searchParams.get('tmdbId')).toBe('123');await shareShowWithFallback({tmdbId:123,mediaType,title:'Public title'},callbacks);expect(write.mock.calls[0][0]).toContain(`mediaType=${mediaType}`);expect(url.searchParams.size).toBe(3);});
it.each([{tmdbId:0,mediaType:'tv'},{tmdbId:'12oops',mediaType:'tv'},{tmdbId:12,mediaType:'person'}])('rejects invalid outgoing identity %j',params=>expect(()=>buildShowShareUrl(params)).toThrow());
describe('privacy-safe snapshots',()=>{
 const movie={id:7,mediaType:'movie',title:'Movie',voteAverage:8.2,userRating:1,userNotes:'PRIVATE-NOTE',tags:['PRIVATE-TAG'],uid:'PRIVATE-UID',email:'PRIVATE-EMAIL',preferredName:'PRIVATE-NAME',progress:'PRIVATE-PROGRESS',reminders:'PRIVATE-REMINDER'};
 const tv={...movie,mediaType:'tv',title:'Series'};
 it('exports only public title/type/TMDB rating',async()=>{const text=formatListShareText('Picks',[movie,tv]);expect(text).toContain('🎬 Movie ⭐ TMDB 8.2/10');expect(text).toContain('📺 Series');expect(text).not.toContain('PRIVATE');expect(text).not.toContain('1.0');await shareListWithFallback({name:'Picks'},[movie],callbacks);expect(write).toHaveBeenCalledWith(text.replace('📺 Series ⭐ TMDB 8.2/10\n',''));});
 it('ratings off never produces false zero ratings or personal ratings',()=>{expect(formatListShareText('Picks',[movie],{includeRatings:false})).not.toContain('⭐');});
 it('compound selection distinguishes collisions and deduplicates within named sections',()=>{const sections=[{name:'Watching',items:[movie,movie,tv]},{name:'Picks',items:[movie]}];const text=formatShareSections(sections,new Set(['movie:7']),true);expect(text.match(/🎬 Movie/g)).toHaveLength(2);expect(text).not.toContain('Series');expect(text).toContain('📋 Watching');expect(text).toContain('📋 Picks');});
 it('explicit none never becomes all; handle is opt-in only',()=>{expect(formatShareSections([{name:'Picks',items:[movie]}],new Set(),true)).not.toContain('Movie');expect(formatShareSections([{name:'Picks',items:[movie]}],new Set(['movie:7']),true)).not.toContain('@');expect(formatShareSections([{name:'Picks',items:[movie]}],new Set(['movie:7']),true,'handle')).toContain('@handle');});
});

it('invalid outgoing identity reports one failure without invoking platform sharing',async()=>{expect(await shareShowWithFallback({tmdbId:'bad',mediaType:'movie',title:'Title'},callbacks)).toBe('failed');expect(error).toHaveBeenCalledOnce();expect(success).not.toHaveBeenCalled();expect(write).not.toHaveBeenCalled();expect(native).not.toHaveBeenCalled();});
