import { act, cleanup, fireEvent, render, screen, within, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import NotInterestedModal from '../modals/NotInterestedModal';
import NotesAndTagsModal from '../modals/NotesAndTagsModal';
import { useState } from 'react';
import type { LibraryEntry } from '../../lib/storage';
import { Library, flushPendingSaves } from '../../lib/storage';
import { languageManager } from '../../lib/language';
const m=vi.hoisted(()=>({ confirm:vi.fn(), canWrite:true, close:vi.fn() }));
vi.mock('../../lib/auth',()=>({authManager:{getCurrentUser:()=>null}}));
vi.mock('../../lib/customLists',()=>({customListManager:{updateItemCount:vi.fn()}}));
vi.mock('../../lib/readOnlyGuard',()=>({guardMutation:()=>m.canWrite}));
vi.mock('../../state/confirm',()=>({confirmAction:m.confirm}));
vi.mock('../../lib/tmdb',()=>({getTVShowDetails:vi.fn().mockRejectedValue(Error('offline'))}));
const data={id:'8',title:'Same ID title',userRating:4,userNotes:'Notes',tags:['tag'],isFavorite:true,customListIds:['a','b']};
beforeEach(()=>{localStorage.clear();window.dispatchEvent(new Event('library:cleared'));languageManager.setLanguage('en');m.canWrite=true;m.close.mockClear();m.confirm.mockReset().mockResolvedValue(false);Library.upsert({...data,mediaType:'movie'},'not');Library.upsert({...data,mediaType:'tv'},'not');localStorage.setItem('episode-progress-8','{"episodes":{"S1E1":true}}');});
afterEach(()=>{cleanup();flushPendingSaves();vi.restoreAllMocks();});
const open=()=>render(<NotInterestedModal isOpen onClose={m.close}/>);
it.each([['Watching','watching'],['Want to Watch','wishlist'],['Watched','watched']] as const)('restores movie to %s without affecting same-ID TV or metadata',async(label,status)=>{open();expect(screen.getByRole('dialog')).toHaveAccessibleName('Not Interested List (2)');fireEvent.click(within(screen.getByTestId('not-interested-movie:8')).getByRole('button',{name:label,exact:true}));expect(screen.queryByTestId('not-interested-movie:8')).toBeNull();expect(Library.getEntry('8','movie')).toMatchObject({...data,list:status});expect(Library.getCurrentList('8','tv')).toBe('not');expect(Library.getByList('not')).toHaveLength(1);expect(Library.getByList(status)).toHaveLength(1);expect(localStorage.getItem('episode-progress-8')).not.toBeNull();});
it('confirmation and cancellation state belongs only to selected compound identity',async()=>{let confirm!:(v:boolean)=>void;m.confirm.mockImplementation(()=>new Promise<boolean>(r=>confirm=r));open();fireEvent.click(within(screen.getByTestId('not-interested-tv:8')).getByRole('button',{name:'Remove from Library',exact:true}));expect(within(screen.getByTestId('not-interested-tv:8')).getByRole('status')).toHaveTextContent('Waiting for confirmation');expect(within(screen.getByTestId('not-interested-movie:8')).queryByRole('status')).toBeNull();await act(async()=>confirm(false));expect(screen.queryByRole('status')).toBeNull();expect(Library.getByList('not')).toHaveLength(2);});
it('confirmed asynchronous deletion stays Removing until completed and only removes selected media',async()=>{m.confirm.mockResolvedValue(true);const original=Library.remove;let done!:()=>void;vi.spyOn(Library,'remove').mockImplementation(((id,kind)=>new Promise<void>(resolve=>{done=()=>{original(id,kind);resolve();};})) as typeof Library.remove);open();fireEvent.click(within(screen.getByTestId('not-interested-movie:8')).getByRole('button',{name:'Remove from Library',exact:true}));expect(await screen.findByRole('status')).toHaveTextContent('Removing');await act(async()=>done());expect(screen.queryByRole('status')).toBeNull();expect(Library.getCurrentList('8','tv')).toBe('not');expect(screen.queryByTestId('not-interested-movie:8')).toBeNull();});
it('removal failure clears pending state and reports an error without success',async()=>{m.confirm.mockResolvedValue(true);vi.spyOn(Library,'remove').mockImplementation(()=>{throw Error('storage failure')});open();fireEvent.click(within(screen.getByTestId('not-interested-movie:8')).getByRole('button',{name:'Remove from Library',exact:true}));expect(await screen.findByRole('alert')).toHaveTextContent('could not be completed');expect(screen.queryByRole('status')).toBeNull();expect(Library.getByList('not')).toHaveLength(2);});
it('read-only restrictions apply to restore and removal',async()=>{open();m.canWrite=false;const row=within(screen.getByTestId('not-interested-movie:8'));fireEvent.click(row.getByRole('button',{name:'Watching',exact:true}));fireEvent.click(row.getByRole('button',{name:'Remove from Library',exact:true}));await waitFor(()=>expect(screen.queryByRole('status')).toBeNull());expect(m.confirm).not.toHaveBeenCalled();expect(Library.getByList('not')).toHaveLength(2);});
it('translated dialog supports Close, Escape and dialog associations',async()=>{languageManager.setLanguage('es');open();await waitFor(()=>expect(screen.getByRole('dialog')).toHaveAccessibleName('Lista de No Me Interesa (2)'));expect(screen.getByRole('dialog')).toHaveAttribute('aria-describedby','not-interested-description');expect(screen.getAllByRole('button',{name:'Eliminar de la biblioteca',exact:true})).toHaveLength(2);fireEvent.keyDown(window,{key:'Escape'});expect(m.close).toHaveBeenCalledOnce();fireEvent.click(screen.getByRole('button',{name:'Cerrar lista de No Me Interesa'}));expect(m.close).toHaveBeenCalledTimes(2);});

it('Notes & Tags delegates canonical editing without restoring title or changing reminders',async()=>{const reminder='{"8":{"enabled":false}}';localStorage.setItem('flicklet.series-reminders.v1',reminder);const edit=vi.fn(item=>Library.updateNotesAndTags(item.id,item.mediaType,'New',['Family']));render(<NotInterestedModal isOpen onClose={m.close} onNotesEdit={edit}/>);fireEvent.click(await within(screen.getByTestId('not-interested-tv:8')).findByRole('button',{name:'Notes & Tags'}));expect(Library.getEntry('8','tv')).toMatchObject({list:'not',userNotes:'New',tags:['Family'],customListIds:['a','b']});expect(localStorage.getItem('flicklet.series-reminders.v1')).toBe(reminder);expect(localStorage.getItem('episode-progress-8')).not.toBeNull();});

it('nested editor consumes Android Back without dismissing Not Interested management',async()=>{
 function Nested(){const [item,setItem]=useState<LibraryEntry|null>(null);return <><NotInterestedModal isOpen onClose={m.close} onNotesEdit={setItem} notesEditorOpen={!!item}/>{item&&<NotesAndTagsModal item={item} isOpen onClose={()=>setItem(null)} onSave={()=>true}/>}</>}
 render(<Nested/>);fireEvent.click(await within(screen.getByTestId('not-interested-tv:8')).findByRole('button',{name:'Notes & Tags'}));expect(screen.getAllByRole('dialog')).toHaveLength(2);act(()=>{window.dispatchEvent(new Event('flicklet:android-back',{cancelable:true}));});expect(screen.getAllByRole('dialog')).toHaveLength(1);expect(m.close).not.toHaveBeenCalled();
});
