# FlickWord + FlickTrivia - focused audit script
# Only includes files that specifically mention FlickWord or FlickTrivia

$ErrorActionPreference = "Stop"

# 1. Make a temp workspace
$REPORT = "$env:TEMP\flick_games_audit.md"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
"# FlickGames Deep-Dive Report - $timestamp" | Out-File -FilePath $REPORT -Encoding utf8
"" | Out-File -FilePath $REPORT -Append -Encoding utf8
"*Generated by focused search for FlickWord and FlickTrivia specific files*" | Out-File -FilePath $REPORT -Append -Encoding utf8
"" | Out-File -FilePath $REPORT -Append -Encoding utf8

# 2. Helper: append file with nice header
function Add-Section {
    param(
        [string]$Title,
        [string]$Path
    )
    
    if (-not (Test-Path $Path)) {
        return
    }
    
    "" | Out-File -FilePath $REPORT -Append -Encoding utf8
    "## $Title" | Out-File -FilePath $REPORT -Append -Encoding utf8
    '```' | Out-File -FilePath $REPORT -Append -Encoding utf8
    
    # Read file content and strip secrets
    $content = Get-Content $Path -Raw -ErrorAction SilentlyContinue
    if ($content) {
        $content = $content -replace '(apiKey|appId|measurementId|Stripe\.key|STRIPE_|REACT_APP_)[^,"]*"', '$1[REDACTED]'
        $content | Out-File -FilePath $REPORT -Append -Encoding utf8
    }
    
    '```' | Out-File -FilePath $REPORT -Append -Encoding utf8
}

# 3. Find files that specifically mention FlickWord or FlickTrivia (case-insensitive)
Write-Host "Searching for FlickWord/FlickTrivia specific files..."
$gameFiles = Get-ChildItem -Path . -Recurse -File `
    -Exclude "*.log", "*.html", "*.csv" `
    | Where-Object {
        $excludeDirs = @("node_modules", ".git", "dist", "build", ".next", "Lighthouse Reports", "test-results")
        $relativePath = $_.FullName.Replace((Get-Location).Path + "\", "")
        -not ($excludeDirs | Where-Object { $relativePath -like "*\$_\*" })
    } `
    | Select-String -Pattern "(FlickWord|FlickTrivia|flickword|flicktrivia)" -CaseSensitive:$false -List `
    | Select-Object -ExpandProperty Path -Unique `
    | Sort-Object

Write-Host "Found $($gameFiles.Count) files"

# 4. Organize by file type/function
$categories = @{
    "Routing & Navigation" = @()
    "Components - UI" = @()
    "Components - Game Logic" = @()
    "Styles" = @()
    "Hooks & Utilities" = @()
    "State & Context" = @()
    "Firebase & Backend" = @()
    "Tests" = @()
    "Documentation" = @()
    "Config & Scripts" = @()
    "Other" = @()
}

foreach ($file in $gameFiles) {
    $name = [System.IO.Path]::GetFileName($file).ToLower()
    $ext = [System.IO.Path]::GetExtension($file).TrimStart('.')
    $relativePath = $file.Replace((Get-Location).Path + "\", "")
    
    if ($relativePath -like "*route*" -or $relativePath -like "*navigation*" -or $relativePath -like "*App.tsx") {
        $categories["Routing & Navigation"] += $file
    }
    elseif ($relativePath -like "*components\games\*" -or $name -like "*game*.tsx" -or $name -like "*game*.ts") {
        $categories["Components - Game Logic"] += $file
    }
    elseif ($relativePath -like "*components\*" -and ($ext -eq "tsx" -or $ext -eq "jsx")) {
        $categories["Components - UI"] += $file
    }
    elseif ($ext -eq "css" -or $ext -eq "scss" -or $name -like "*style*") {
        $categories["Styles"] += $file
    }
    elseif ($relativePath -like "*hooks\*" -or $relativePath -like "*utils\*" -or $relativePath -like "*lib\*") {
        $categories["Hooks & Utilities"] += $file
    }
    elseif ($relativePath -like "*store*" -or $relativePath -like "*context*" -or $relativePath -like "*state*") {
        $categories["State & Context"] += $file
    }
    elseif ($relativePath -like "*firebase*" -or $relativePath -like "*firestore*" -or $relativePath -like "*functions\*") {
        $categories["Firebase & Backend"] += $file
    }
    elseif ($relativePath -like "*test*" -or $relativePath -like "*spec*" -or $relativePath -like "*e2e*") {
        $categories["Tests"] += $file
    }
    elseif ($relativePath -like "*docs\*" -or $relativePath -like "*.md" -or $relativePath -like "*README*") {
        $categories["Documentation"] += $file
    }
    elseif ($relativePath -like "*config*" -or $relativePath -like "*scripts\*" -or $name -like "package.json" -or $name -like "*.config.*") {
        $categories["Config & Scripts"] += $file
    }
    else {
        $categories["Other"] += $file
    }
}

# 5. Write organized report
foreach ($category in $categories.Keys | Sort-Object) {
    $files = $categories[$category]
    if ($files.Count -eq 0) { continue }
    
    "" | Out-File -FilePath $REPORT -Append -Encoding utf8
    "# $category" | Out-File -FilePath $REPORT -Append -Encoding utf8
    "*$($files.Count) file(s)*" | Out-File -FilePath $REPORT -Append -Encoding utf8
    "" | Out-File -FilePath $REPORT -Append -Encoding utf8
    
    foreach ($file in $files | Sort-Object) {
        $relativePath = $file.Replace((Get-Location).Path + "\", "")
        Add-Section -Title $relativePath -Path $file
    }
}

# 6. Quick stats
"" | Out-File -FilePath $REPORT -Append -Encoding utf8
"# Quick Stats" | Out-File -FilePath $REPORT -Append -Encoding utf8
"| Term | File Count |" | Out-File -FilePath $REPORT -Append -Encoding utf8
"|------|------------|" | Out-File -FilePath $REPORT -Append -Encoding utf8

$terms = @("FlickWord", "FlickTrivia", "flickword", "flicktrivia")
foreach ($term in $terms) {
    $fileCount = ($gameFiles | Where-Object {
        $content = Get-Content $_ -Raw -ErrorAction SilentlyContinue
        $content -and $content -match [regex]::Escape($term)
    } | Measure-Object).Count
    
    "| $term | $fileCount |" | Out-File -FilePath $REPORT -Append -Encoding utf8
}

# 7. Summary
"" | Out-File -FilePath $REPORT -Append -Encoding utf8
"# Summary" | Out-File -FilePath $REPORT -Append -Encoding utf8
"Total files analyzed: $($gameFiles.Count)" | Out-File -FilePath $REPORT -Append -Encoding utf8
"" | Out-File -FilePath $REPORT -Append -Encoding utf8
"_Report generated at $REPORT _" | Out-File -FilePath $REPORT -Append -Encoding utf8

Write-Host "Report generated at: $REPORT"
Write-Host "Total files: $($gameFiles.Count)"

# Open the file
Start-Process "cursor" -ArgumentList "`"$REPORT`"" -ErrorAction SilentlyContinue
if ($LASTEXITCODE -ne 0) {
    Start-Process "code" -ArgumentList "`"$REPORT`"" -ErrorAction SilentlyContinue
    if ($LASTEXITCODE -ne 0) {
        Invoke-Item $REPORT
    }
}

Write-Host "Done!"
















