import { t } from "./language";
const GENRE_LABEL_KEYS = {
  "Anime": "coreGenreAnime",
  "Shōnen": "coreGenreShnen",
  "Shōjo": "coreGenreShjo",
  "Mecha": "coreGenreMecha",
  "Fantasy": "coreGenreFantasy",
  "Romance": "coreGenreRomance",
  "Comedy": "coreGenreComedy",
  "Popular": "coreGenrePopular",
  "Sports": "coreGenreSports",
  "Horror": "coreGenreHorror",
  "Animation": "coreGenreAnimation",
  "Family": "coreGenreFamily",
  "Action": "coreGenreAction",
  "Adventure": "coreGenreAdventure",
  "Musical": "coreGenreMusical",
  "Psychological": "coreGenrePsychological",
  "Supernatural": "coreGenreSupernatural",
  "Slasher": "coreGenreSlasher",
  "Gothic": "coreGenreGothic",
  "Found Footage": "coreGenreFoundFootage",
  "Body Horror": "coreGenreBodyHorror",
  "Romantic": "coreGenreRomantic",
  "Dark": "coreGenreDark",
  "Satirical": "coreGenreSatirical",
  "Slapstick": "coreGenreSlapstick",
  "Parody": "coreGenreParody",
  "Stand-up": "coreGenreStandup",
  "Drama": "coreGenreDrama",
  "Period": "coreGenrePeriod",
  "Legal": "coreGenreLegal",
  "Medical": "coreGenreMedical",
  "Political": "coreGenrePolitical",
  "Crime": "coreGenreCrime",
  "Martial Arts": "coreGenreMartialArts",
  "Spy": "coreGenreSpy",
  "War": "coreGenreWar",
  "Superhero": "coreGenreSuperhero",
  "Thriller": "coreGenreThriller",
  "Science Fiction": "coreGenreScienceFiction",
  "Sci-Fi": "coreGenreSciFi",
  "Space Opera": "coreGenreSpaceOpera",
  "Cyberpunk": "coreGenreCyberpunk",
  "Dystopian": "coreGenreDystopian",
  "Time Travel": "coreGenreTimeTravel",
  "Alien": "coreGenreAlien",
  "Post-Apocalyptic": "coreGenrePostApocalyptic",
  "High Fantasy": "coreGenreHighFantasy",
  "Urban Fantasy": "coreGenreUrbanFantasy",
  "Dark Fantasy": "coreGenreDarkFantasy",
  "Fairy Tale": "coreGenreFairyTale",
  "Mythology": "coreGenreMythology",
  "Magic": "coreGenreMagic",
  "Romantic Comedy": "coreGenreRomanticComedy",
  "Young Adult": "coreGenreYoungAdult",
  "Erotic": "coreGenreErotic",
  "LGBTQ+": "coreGenreLGBTQ",
  "Historical": "coreGenreHistorical",
  "Documentary": "coreGenreDocumentary",
  "Nature": "coreGenreNature",
  "Biographical": "coreGenreBiographical",
  "Social": "coreGenreSocial",
  "Scientific": "coreGenreScientific",
  "True Crime": "coreGenreTrueCrime",
  "History": "coreGenreHistory",
  "Music": "coreGenreMusic",
  "Mystery": "coreGenreMystery",
  "TV Movie": "coreGenreTVMovie",
  "Western": "coreGenreWestern"
} as const;
/** Display only: never pass labels back into stored IDs or API requests. */
export function genreDisplayName(name: string): string {
 const key = GENRE_LABEL_KEYS[name as keyof typeof GENRE_LABEL_KEYS];
 return key ? t(key) : name;
}
